version: 2.0

jobs:
  Python_3.6:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/sanic-starter/api
    steps: &steps
      - checkout
      - run: sudo pip install -r api/requirements.txt
      - run: sudo pip install flake8
      - run: flake8 --exclude mongo_data,nginx,redis_data,migrations,venv,__init__.py,__pycache__ --ignore=E999 api

workflows:
  version: 2
  build:
    jobs:
      - Python_3.6
